version: '3.8'

services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      DEBUG: nodejs-docker-express:*
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

volumes:
  mosquitto-data: