version: '3.8'

services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      DEBUG: nodejs-docker-express:*

  # zookeeper:
  #   image: bitnami/zookeeper:3.8
  #   ports:
  #     - "2181:2181"
  #   volumes:
  #     - zookeeper-data:/bitnami
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_LOG_LEVEL=WARN

  # kafka:
  #   image: bitnami/kafka:3.1
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - kafka-data:/bitnami
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=kafka-internal.io
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
  #     - KAFKA_LOG_LEVEL=WARN
  #   depends_on:
  #     - zookeeper
      
  # mosquitto:
  #   image: eclipse-mosquitto:latest
  #   volumes:
  #     - mosquitto-data:/mosquitto/data
  #     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #   ports:
  #     - "1883:1883"

# volumes:
#   kafka-data:
#   zookeeper-data:
  # mosquitto-data: